// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using milk_in_liters_api.database;

#nullable disable

namespace milk_in_liters_api.Migrations
{
    [DbContext(typeof(datacontext))]
    [Migration("20220924075128_type_chnage_of_milk_from_int_to_float")]
    partial class type_chnage_of_milk_from_int_to_float
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("milk_in_liters_api.model.member", b =>
                {
                    b.Property<int>("member_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("member_Id"), 1L, 1);

                    b.Property<string>("aadhar_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<string>("member_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("member_Id");

                    b.ToTable("members");
                });

            modelBuilder.Entity("milk_in_liters_api.model.milk", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime2");

                    b.Property<float>("liters")
                        .HasColumnType("real");

                    b.Property<int>("member_Id")
                        .HasColumnType("int");

                    b.Property<int>("shift")
                        .HasColumnType("int");

                    b.Property<float>("total_liters")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("member_Id");

                    b.ToTable("milks");
                });

            modelBuilder.Entity("milk_in_liters_api.model.milk", b =>
                {
                    b.HasOne("milk_in_liters_api.model.member", "memberss")
                        .WithMany()
                        .HasForeignKey("member_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("memberss");
                });
#pragma warning restore 612, 618
        }
    }
}
